version: "3.9"

services:
  db:
    image: postgres:16
    container_name: conta_corrente_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ContaCorrenteDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: conta_corrente_app
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ContaCorrenteDB;Username=postgres;Password=postgres
    ports:
      - "8080:8081"
    volumes:
      - .:/app

volumes:
  pgdata:
